
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.XSExtra
{
	public partial class PromptFileName
	{
		private global::Gtk.Label label1;
		private global::Gtk.Entry _newFileName;
		private global::Gtk.CheckButton _searchAndReplace;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.XSExtra.PromptFileName
			this.Name = "MonoDevelop.XSExtra.PromptFileName";
			this.Title = global::Mono.Unix.Catalog.GetString ("Duplicate File");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			// Internal child MonoDevelop.XSExtra.PromptFileName.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("_New Name:");
			this.label1.UseUnderline = true;
			w1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this._newFileName = new global::Gtk.Entry ();
			this._newFileName.CanFocus = true;
			this._newFileName.Name = "_newFileName";
			this._newFileName.IsEditable = true;
			this._newFileName.ActivatesDefault = true;
			this._newFileName.InvisibleChar = '●';
			w1.Add (this._newFileName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this._newFileName]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this._searchAndReplace = new global::Gtk.CheckButton ();
			this._searchAndReplace.CanFocus = true;
			this._searchAndReplace.Name = "_searchAndReplace";
			this._searchAndReplace.Label = global::Mono.Unix.Catalog.GetString ("_Update Name in File Contents");
			this._searchAndReplace.Active = true;
			this._searchAndReplace.DrawIndicator = true;
			this._searchAndReplace.UseUnderline = true;
			w1.Add (this._searchAndReplace);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this._searchAndReplace]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child MonoDevelop.XSExtra.PromptFileName.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			w5.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 458;
			this.DefaultHeight = 156;
			this.label1.MnemonicWidget = this.label1;
			this.buttonOk.HasDefault = true;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnOK);
		}
	}
}
